"""empty message

Revision ID: d05d3f7e4705
Revises: 
Create Date: 2024-11-20 11:58:52.324224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05d3f7e4705'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents_instagram',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('types_content', sa.String(), nullable=True),
    sa.Column('number_views', sa.Integer(), nullable=True),
    sa.Column('number_likes', sa.Integer(), nullable=True),
    sa.Column('number_comments', sa.Integer(), nullable=True),
    sa.Column('view_content', sa.String(), nullable=True),
    sa.Column('updating_data', sa.Date(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('data_add', sa.Date(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('instagram_page_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instagram_page_id'], ['instagram_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents_youtube',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('types_content', sa.String(), nullable=True),
    sa.Column('number_views', sa.Integer(), nullable=True),
    sa.Column('number_likes', sa.Integer(), nullable=True),
    sa.Column('number_comments', sa.Integer(), nullable=True),
    sa.Column('updating_data', sa.Date(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('data_add', sa.Date(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('youtube_channels_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['youtube_channels_id'], ['youtube_channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_subtitles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subtitles_text', sa.Text(), nullable=True),
    sa.Column('contents_youtube_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contents_youtube_id'], ['contents_youtube.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youtube_subtitles')
    op.drop_table('contents_youtube')
    op.drop_table('contents_instagram')
    op.drop_table('youtube_channels')
    op.drop_table('instagram_pages')
    # ### end Alembic commands ###
