"""empty message

Revision ID: d924895ead8f
Revises: d05d3f7e4705
Create Date: 2024-11-20 12:08:17.905133

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'd924895ead8f'
down_revision: Union[str, None] = 'd05d3f7e4705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
